[shell]
program = '/opt/homebrew/bin/fish'
args = ['-c tmux']

[font]
normal = { family = 'FiraCode Nerd Font', style = 'Regular' }

bold = { family = 'FiraCode Nerd Font', style = 'Regular' } # disable bold font


